### ISSUE TITLE
I can still see the API keys you're trying to hide.

### ISSUE THREAD

**Issue by RainbowAsteroids** [DylanHamer/RedditThing#1]
Apparently, GitHub allows you to look into the past and see the changes other recent commits did on older more outdated commits. I recommend deleting this repo and the other reddit one to so that way you're secure.

https://github.com/DylanHamer/RedditThing/commit/6d6bc70f1ea817e4d35f58d50f4fe48e34cf29ad

**Comment by DylanHamer** [comment]
Yeah, I know. I realised and just decided to delete the keys from my
account. Thanks for the info, though.
